### ISSUE TITLE
'Install on' is an object group

### ISSUE THREAD

**Issue by flamery** [CheckPointSW/PolicyCleanUp#3]
When running this tool against a policy where the "install on" is an object group (rather than a gateway) all rules in this policy are skipped.

R77.xx did not allow an object group in the install on field but since R80.xx it is allowed.

**Comment by chkp-niram** [comment]
Hey @flamery ,
Thanks for the input.
Did the tool report skipping the package or was it something you had to figure out?
Also, was any error message shown?

**Comment by flamery** [comment]
Hi, the script seems to handle it gracefully, for every rule in the policy I get a message like this in the output:

"skipped-reason": "target with UID 9f850f4e-6551-40af-9fa1-fb4527e13166 in the install-on list is invalid",

Where-as running against a different policy without a group in use it seems to work perfectly fine.

**Comment by chkp-niram** [comment]
@flamery Thanks.
We'll consider adding the ability to support groups in install-on for the next release.
I'll update the issue with our decision.

**Comment by chkp-yaelg** [comment]
Hey @flamery , thanks for your feedback.

We checked it and we added the ability to support groups in install-on.
You cen check it in the [last release](https://github.com/CheckPointSW/PolicyCleanUp/releases/tag/V1.0.1).

Thanks again and I encourage you to keep suggesting improvements and fixes to our repositories.
