### ISSUE TITLE
Change to rule

### ISSUE THREAD

**Issue by bhaizlett123** [CheckPointSW/PolicyCleanUp#6]
Hello,
 First off I would like to say this tool is awesome and works great, but i think i found an issue with it. I noticed that if i make a change to the rule, but the hit count doesn't change, it doesn't add it as one of the rules to disable, even though it should be since the hitcount threshold is within the specified time for rules to be disabled.

I tested it with a rule that prior to me making a change was in teh disabled list, and then i made a change to the comments of the rule and installed database and then ran the tool again and it didn't add it to the disabled list.

**Comment by chkp-yaelg** [comment]
Hi @bhaizlett123 ,
Thank you for your feedback! We are happy to see you find this tool useful.

According to the issue you mentioned - actually the tool is planned that way.
We are using a save approach - we are keeping rules enabled in case that they have been changed.
In case of change in comment it might be unnecessary but if you changed the source list - it might effect on the hits in the future.

Hope it is clear now.
