### ISSUE TITLE
show mdss API call from wrong context

### ISSUE THREAD

**Issue by Senas23** [CheckPointSW/PolicyCleanUp#8]
The API call **show-mdss** used to work from any CMA (bug), and it's supposed to be called from the **'System Data'** aka **MDS** domain only (fix).
Please fix the code to make the API call **show-mdss** against the 'System Data' domain.
Function: **check_validation_for_mds**
Thank you!

**Comment by chkp-royl** [comment]
Hi @Senas23 ,
Thank you for posting this issue.
We will fix this bug as soon as possible.

Thanks,
Roy

**Comment by chkp-royl** [comment]
Hi @Senas23 ,
We released new version of the tool (v1.0.2) include fix for this bug.

Thanks,
Roy
